### ISSUE TITLE
Azure OpenAI API Key Invalid

### ISSUE THREAD

**Issue by Explorergt92** [microsoft/vscode-copilot-vision#70]
Created a new gpt-4o deployment in Azure, changed the Copilot > Vision: Provider to AzureOpenAI and tried to copy and paste an image into the chat and it prompts me to enter the Azure OpenAI API Key but tells me the API key from Azure OpenAI is invalid, but it never asks me for an Azure OpenAI endpoint, I have also tried a Global Provisioning of the gpt-4o model with the same result.

**Comment by justschen** [comment]
hey! sorry about that, our `AzureOpenAI` endpoint is actually intended for internal use only atm (we're using a VS Code azure endpoint).  

We'll work on adding that in the future potentially, but should have no issues with Gemini, Anthropic, or OpenAI since those have universal endpoints

**Comment by MoazAlkharfan** [comment]
@justschen 
OpenAI api key is also giving the error invalid.

**Comment by alexander-kastil** [comment]
@justschen I consider this a "strange reply". You are using an LLM hosted on Azure, you are extending a Microsoft Product (Copilot) and want others to use non-Microsoft endpoints? Opened another issue https://github.com/microsoft/vscode-copilot-vision/issues/73

**Comment by justschen** [comment]
fixed with https://github.com/microsoft/vscode-copilot-vision/pull/74
