### ISSUE TITLE
Support Models deployed to Azure Open AI

### ISSUE THREAD

**Issue by alexander-kastil** [microsoft/vscode-copilot-vision#73]
It would be great if you could also support models deployed on Azure (or using Azure AI Studio) ... As an Azure developer working a lot with Microsoft tech stacks, this is where I consume / host my LLM's

**Comment by justschen** [comment]
hey @alexander-kastil we pushed a fix for this so selecting azure open ai should prompt you to include an endpoint. you can also set this in settings. lmk if it works :D
