### ISSUE TITLE
Canceling "Refine alt text" still triggers a Chat request

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-copilot-vision#78]
Type: <b>Bug</b>

CC @meganrogge 

1. Create alt text in md file for any image

2. In action, click "Refine alt text"

3. Without typing anything, press ESC to destroy the refinement input

## Current Behavior

Cancelling refinement still sends a Chat request

## Expected Behavior

Don't send any request if it's destroyed.

Extension version: 0.2.2024110422
VS Code version: Code - Insiders 1.96.0-insider (399779942db4d7ab1bd6f6ae976482d0020f10ca, 2024-11-13T05:04:32.098Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.53GB free)|
|Process Argv|C:\\Users\\jseo1005\\OneDrive - University of Illinois - Urbana\\Desktop\\todo.md --crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
01bff139:31013167
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054

```

</details>

**Comment by meganrogge** [comment]
Thanks for the issue. I fixed this yesterday, but need to create a new build. https://github.com/microsoft/vscode-copilot-vision/pull/77

**Comment by meganrogge** [comment]
Will do so now!
