### ISSUE TITLE
Invalid Key: Not working with both Azure OpenAI and OpenAI

### ISSUE THREAD

**Issue by ambilykk** [microsoft/vscode-copilot-vision#82]
Hello Team

I have created an Azure OpenAI resource and passed the endpoint through the extension settings. But, @vision throws invalid API key message.

Tried by OpenAI Key, but the result is same - "Invalid Key"

![Image](https://github.com/user-attachments/assets/4cac474d-31ea-456b-bdf2-6320ff2a17c3)

**Comment by justschen** [comment]
@ambilykk hey! sorry our documentation needs a little updating, but in both scenarios, there has to be a positive $ of credit in the account for it to work.

**Comment by ambilykk** [comment]
@justschen 
I have an Azure subscription with a credit balance and have set up Azure OpenAI within the same subscription.

**Comment by justschen** [comment]
@ambilykk in the azure open ai studio, can you double check that you're using the correct endpoint (target uri) and that the deployment names match up?

**Comment by ambilykk** [comment]
Thank you @justschen; I am able to configure the Vision extension.

Initially I have passed the OpenAII endpoint from Azure portal. That doesn't work.
Now, I have used the URL from the deployment; something like the below
https://xxxx.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2024-08-01-preview

Please update the document with the expected API URL details.
