### ISSUE TITLE
Why vision requires an open api key

### ISSUE THREAD

**Issue by samuel-ek** [microsoft/vscode-copilot-vision#87]
Type: <b>Bug</b>

I am trying to use vison in copilot it is asking for open ai key

Extension version: 0.2.2024111316
VS Code version: Code - Insiders 1.97.0-insider (95386dec787946547812c7ee9d38cba19d6a6398, 2024-12-17T05:04:19.511Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by justschen** [comment]
we've mentioned that this is a "bring your own key model". it's intended to be a preview of what will eventually be in copilot chat!
